language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: cvall018
  password:
    secure: ffaJbgfGQ6Vkwt84WVdoeGI6E8YFe9rmEOpNKHxkPfEyyZaqiKQ3lIlFStFtPpwo4hZ6QvV1ZA2ArQzNG6oP9NSrakdBrIyJul6k09NrgKZcQG9dvDel24Fvfcr+uSiv4c461Qkr4eyoD/bLc68YHjg7HDOyDMw5GDGw0df6eHV3N4uTdRPhaPA2jgRAmbewTilgd+aMYfny0rIj/zXAOE08eTn1Oh1g9kAMOOqkjW3aiOrSgaVdhI3GezIRmZYeavpykmjUVuRq1+uWZvcfji26C2YeZCAGfRJpLMqO+hGy172AnRPD08USTvu/AoF+ljEuv+xvC7dyPG6EWPeYLvDUdLmk1E8F5nHLPtZK9e681G/5BSCVdi3vFZUfEJ8RGn1mtH0cYVHwilgcMrFkLgMKzGw+O9/e6eECZEIqoLQm7uA6VtNKF5FepMPraFW5zKVhhRTVRdeVjkjC09hkzrqrStr9rP3F6/GhjYnub3QWVwws5Oy25osOWJwo6Ap4S8/rcLxa390o9tngSrUx2Tt6pIFmiO0jtw6xbTMUMLnj/AdK9vgW+rsDUNSe1satVqjBiDe3grj0HeWfmiSgMqA7NHOPwQCEqossbwiNuQbm5/QA2O89qs0uJ4HTjNMt/r8e2Dw147bxpemcXSXxV2dUhw9WtS+IhTW7+oy+3TE=
  on:
    tags: true
    repo: cvall018/cookiecuttertest
    python: 3.8
